Refactor Azure Pipeline workflow to add user authorization check

diff --git a/.github/workflows/publish-package.yml b/.github/workflows/publish-package.yml
--- a/.github/workflows/publish-package.yml
+++ b/.github/workflows/publish-package.yml
@@ -11,6 +11,12 @@ jobs:
   trigger-pipeline:
     runs-on: ubuntu-latest
     steps:
+      - name: Check if user is authorized
+        run: |
+          if [[ "$GITHUB_ACTOR" != "Adu2120" ]]; then
+            echo "Error: Unauthorized user. Exiting."
+            exit 1
+
       - name: Publish to Azure DevOps
         run: |
           az devops configure --defaults organization=https://dev.azure.com/adityakavale project=adityakavale
